### ISSUE TITLE
Throttling per request (not per group)

### ISSUE THREAD

**Issue by md-tfabi** [TreeGateway/tree-gateway#163]
Does TreeGateway let us setup throttling based on requests (per user), rather than groups?
So I have 3 users hitting the same endpoint, but I still want one of them to have different thresholds.
The user id is in the request header.
Is there a way of achieving this within TreeGateway?

**Comment by thiagobustamante** [comment]
Hi @md-tfabi ,

Yes, it is possible, but you need to inform your own middleware for throttling origin identification (keyGenerator):

for example:
```yml
---
name: MyThrottledAPI
version: 1.0.0
path: throttled/
proxy:
    target:
        host: http://httpbin.org
throttling:
    timeWindow: 1 minute
    max: 250 
    keyGenerator:
        name: myKeyGen
```

And then create the middleware ```myKeyGen```:

```javascript
"use strict";

module.exports = function (request) {
    return request.headers['user_id'];
};
```
